function chargesurfop = makeSurfaceToChargePanelOperators(surf, pqr)
disp("From makeSurfaceToChargePanelOperators");
[phiCoul, dphidnCoul] = coulombMatrixCollocation(surf.meshData, ...
						 surf.centroids, ...
						 surf.normals, ...
						 pqr.xyz);

[slpToCharges, dlpToCharges] = ...
    computeChargePotentials(surf.meshData,pqr.xyz);


chargesurfop = struct('phiCoul', phiCoul,...
		      'dphidnCoul',dphidnCoul,...
		      'slpToCharges',slpToCharges,...
		      'dlpToCharges',dlpToCharges);
