function [pKa_nl,pKa_l,Edetails,dE_total_nl, dE_total_l]=estimate_pKa(protPQR,deprotPQR,SRF,E_omega_vec,E_sigma,lambda_vec,E_vac)
global q Na E_0 E_inf joulesPerCalorie kappa
T = 300;
RT = 0.00198721*T;

protonatedPqrData = readpqr(protPQR);
deprotonatedPqrData = readpqr(deprotPQR);

[MeshBase, RootDir] = readsrf(SRF);
MeshData = readmesh(MeshBase,1);
[Centroids,Normals,Areas] = genmeshcolloc(MeshData);
[A] = collocation_mesh(MeshData,Centroids,Normals,Areas);
[protB,protC] = chargeCollocation_mesh(MeshData, ...
													Centroids, ...
													Normals,Areas, ...
													protonatedPqrData);
[deprotB,deprotC] = chargeCollocation_mesh(MeshData, ...
														 Centroids, ...
														 Normals, ...
														 Areas, ...
														 deprotonatedPqrData);
for i=1:length(lambda_vec)
  lambda=lambda_vec(i);
  bigLambda = lambda * sqrt(E_inf/E_sigma);
  kappa = 1/bigLambda;
  [A_Y] = collocation_mesh_Yukawa(MeshData,Centroids,Normals,Areas, ...
											 kappa);
  for j=1:length(E_omega_vec)
	 E_omega = E_omega_vec(j);

	 % protonated species in nonlocal solvent
	 [protAnl,protBnl,protCnl]= ...
		  generate_nonlocal_matrices(A,protB,protC,A_Y, ...
											  Areas,E_0, E_inf,E_omega,E_sigma);
	 x_prot_nl = gmres(protAnl,protBnl*protonatedPqrData.q,[],1e-6,300);
	 E_prot_nl(i,j) = 0.5 * (Na/1000) * (q^2/E_0) * 1e10 ...
		  * (protonatedPqrData.q' * protCnl * x_prot_nl);
	 
	 % protonated species in local solvent
	 [protAl,protBl,protCl]=generate_local_matrices(A, ...
																	protB, ...
																	protC,Areas,E_0, ...
																	E_inf,E_omega, E_sigma);
	 x_prot_l = gmres(protAl,protBl*protonatedPqrData.q,[], 1e-6,300);
	 E_prot_l(i,j) = 0.5 * (Na/1000) * (q^2/E_0) * 1e10 * ...
		  (protonatedPqrData.q' * protCl * x_prot_l);
	 
	 % protonated species in vacuum solvent
	 [protAref,protBref,protCref]= ...
		  generate_local_matrices(A,protB,protC,Areas,E_0, ...
										  E_inf,E_omega, E_vac);
	 x_prot_ref = gmres(protAref,protBref*protonatedPqrData.q,[], ...
							  1e-6,300);
	 E_prot_ref(i,j) = 0.5 * (Na/1000) * (q^2/E_0) * 1e10 ...
		  * (protonatedPqrData.q' * protCref * x_prot_ref);
	 
	 
	 % de protonated species in nonlocal solvent
	 [deprotAnl,deprotBnl,deprotCnl]= ...
		  generate_nonlocal_matrices(A,deprotB,deprotC,A_Y, ...
											  Areas,E_0, E_inf,E_omega,E_sigma);
	 x_deprot_nl = gmres(deprotAnl,deprotBnl*deprotonatedPqrData.q,[],1e-6,300);
	 E_deprot_nl(i,j) = 0.5 * (Na/1000) * (q^2/E_0) * 1e10 ...
		  * (deprotonatedPqrData.q' * deprotCnl * x_deprot_nl);
	 
	 % deprotonated species in local solvent
	 [deprotAl,deprotBl,deprotCl]= ...
		  generate_local_matrices(A,deprotB,deprotC,Areas,E_0, ...
										  E_inf,E_omega, E_sigma);
	 x_deprot_l = gmres(deprotAl,deprotBl*deprotonatedPqrData.q,[], ...
							  1e-6,300);
	 E_deprot_l(i,j) = 0.5 * (Na/1000) * (q^2/E_0) * 1e10 ...
		  * (deprotonatedPqrData.q' * deprotCl * x_deprot_l);
	 
	 % deprotonated species in vacuum solvent
	 [deprotAref,deprotBref,deprotCref]= ...
		  generate_local_matrices(A,deprotB,deprotC,Areas,E_0, ...
										  E_inf,E_omega, E_vac);
	 x_deprot_ref = gmres(deprotAref,deprotBref* ...
								 deprotonatedPqrData.q,[], 1e-6,300);
	 E_deprot_ref(i,j) = 0.5 * (Na/1000) * (q^2/E_0) * ...
		  1e10 * (deprotonatedPqrData.q' * deprotCref * x_deprot_ref);

	 % Coulomb
	 E_prot_Coul(i,j) = getCoulomb(protonatedPqrData,E_omega);
	 E_deprot_Coul(i,j) = getCoulomb(deprotonatedPqrData,E_omega);

  end
end

E_prot_nl_solv = E_prot_nl - E_prot_ref;
E_deprot_nl_solv = E_deprot_nl - E_deprot_ref;
E_prot_l_solv = E_prot_l - E_prot_ref;
E_deprot_l_solv = E_deprot_l - E_deprot_ref;

dE_vac  = E_prot_ref  - E_deprot_ref;

dE_Coul = E_prot_Coul - E_deprot_Coul;

dE_total_nl = -E_deprot_nl_solv + (dE_vac + dE_Coul) + E_prot_nl_solv;
dE_total_l  = -E_deprot_l_solv  + (dE_vac + dE_Coul) + E_prot_l_solv;

pKa_nl = (-dE_total_nl/joulesPerCalorie)/log(10)/RT;
pKa_l =  (-dE_total_l /joulesPerCalorie)/log(10)/RT;
Edetails	= struct('prot_nl',E_prot_nl, ...
						'prot_l', E_prot_l, ...
						'prot_ref', E_prot_ref, ...
						'deprot_nl', E_deprot_nl,...
						'deprot_l', E_deprot_l,...
						'deprot_ref', E_deprot_ref, ...
						'dE_Coul',dE_Coul,...
						'prot_Coul',E_prot_Coul,...
						'deprot_Coul',E_deprot_Coul);
