  figure;
LH1 = plot(E_omega_vec,-(dE_total_l(surfOrBuried,:)-dE_res_total_l)*scaleFact, ...
			  'bo-','linewidth',1.8);
hold on;
set(gca,'FontSize',16);
NLH2 = plot(E_omega_vec,-(dE_l2_total_nl(surfOrBuried,:)- ...
									dE_l2_res_total_nl)*scaleFact, ...
				 'rs--','linewidth',1.8);
NLH5 = plot(E_omega_vec,-(dE_l5_total_nl(surfOrBuried,:)- ...
									dE_l5_res_total_nl)*scaleFact, ...
				 'k^-.','linewidth',1.8);
NLH10 = plot(E_omega_vec,-(dE_l10_total_nl(surfOrBuried,:)- ...
									dE_l10_res_total_nl)*scaleFact, ...
				 'bd:','linewidth',1.8);
NLH15 = plot(E_omega_vec,-(dE_l15_total_nl(surfOrBuried,:)- ...
									dE_l15_res_total_nl)*scaleFact, ...
				 'm*-','linewidth',1.8);
XH1 = xlabel('Solute Dielectric Constant   \epsilon_p');
YH1 = ylabel('\Delta pKa');
LegH1 = legend('Local','Nonlocal, \lambda = 2',...
					'Nonlocal, \lambda = 5',...
					'Nonlocal, \lambda = 10',...
					'Nonlocal, \lambda = 15','location','northeast');
axis([1.8 40 -1.5 5])


figure;
LH1 = plot(E_omega_vec,-(dE_total_l(surfOrBuried,:)- ...
								 dE_res_total_l)*scaleFact, 'bo-','linewidth',1.8);
hold on;
set(gca,'FontSize',16);
NLH2 = plot(E_omega_vec,-(dE_l2_total_nl(surfOrBuried,:)-dE_l2_res_total_nl)*scaleFact,...
				'rs--','linewidth',1.8);
NLH5 = plot(E_omega_vec,-(dE_l5_total_nl(surfOrBuried,:)-dE_l5_res_total_nl)*scaleFact,...
				'k^-.','linewidth',1.8);
NLH10 = plot(E_omega_vec,-(dE_l10_total_nl(surfOrBuried,:)-dE_l10_res_total_nl)*scaleFact,...
				'bd:','linewidth',1.8);
NLH15 = plot(E_omega_vec,-(dE_l15_total_nl(surfOrBuried,:)-dE_l15_res_total_nl)*scaleFact,...
				'm*-','linewidth',1.8);
XH1 = xlabel('Solute Dielectric Constant   \epsilon_p');
YH1 = ylabel('\Delta pKa');
axis([1.8 10 -1.5 3.2]);


