figure; subplot(2,2,1);

LresLoc = plot(E_omega_vec,-(dE_res_total_l-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'ks-','linewidth',1.8);
hold on; set(gca,'Fontsize',16);
Lres2 = plot(E_omega_vec,-(dE_l2_res_total_nl-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'r-','linewidth',1.8);
Lres5 = plot(E_omega_vec,-(dE_l5_res_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'k-.','linewidth',1.8);
Lres10 = plot(E_omega_vec,-(dE_l10_res_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'b:.','linewidth',1.8);
Lres15 = plot(E_omega_vec,-(dE_l15_res_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'m--','linewidth',1.8);
xlabel('Solute Dielectric Constant   \epsilon_p');
ylabel('\Delta G_{solv}^{res}(MH^+\rightarrow M)');
axis([1.8 40 -29 11]);

subplot(2,2,2);
Lburloc = plot(E_omega_vec,-(dE_total_l(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'ks-','linewidth',1.8);
hold on; set(gca,'Fontsize',16);
Lbur2 = plot(E_omega_vec,-(dE_l2_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'r-','linewidth',1.8);
Lbur5 = plot(E_omega_vec,-(dE_l5_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'k-.','linewidth',1.8);
Lbur10 = plot(E_omega_vec,-(dE_l10_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'b:','linewidth',1.8);
Lbur15 = plot(E_omega_vec,-(dE_l15_total_nl(1,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'m--','linewidth',1.8);
xlabel('Solute Dielectric Constant   \epsilon_p');
ylabel('\Delta G_{solv}^{bur}(MH^+\rightarrow M)');
axis([1.8 40 -7 1]);

subplot(2,2,3);
Lsrfloc = plot(E_omega_vec,-(dE_total_l(2,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'ks-','linewidth',1.8);
hold on; set(gca,'Fontsize',16);
Lsrf2 = plot(E_omega_vec,-(dE_l2_total_nl(2,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'r-','linewidth',1.8);
Lsrf5 = plot(E_omega_vec,-(dE_l5_total_nl(2,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'k-.','linewidth',1.8);
Lsrf10 = plot(E_omega_vec,-(dE_l10_total_nl(2,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'b:','linewidth',1.8);
Lsrf15 = plot(E_omega_vec,-(dE_l15_total_nl(2,:)-dE_Coul(1,:))/ ...
			  joulesPerCalorie,'m--','linewidth',1.8);
xlabel('Solute Dielectric Constant   \epsilon_p');
ylabel('\Delta G_{solv}^{surf}(MH^+\rightarrow M)');
LEGH = legend('Local','Nonlocal, \lambda = 2', 'Nonlocal, \lambda = 5', ...
				  'Nonlocal, \lambda = 10','Nonlocal, \lambda = 15',...
				  'location','southeast');
axis([1.8 40 -13 2]);

subplot(2,2,4);
Lloc = plot(E_omega_vec, Elres_deprot_solv/joulesPerCalorie,...
				'ks-', 'linewidth',1.8);
hold on; set(gca,'Fontsize',16);
L2 = plot(E_omega_vec, Enl_l2_res_deprot_solv/joulesPerCalorie,...
				'r-', 'linewidth',1.8);
L5 = plot(E_omega_vec, Enl_l5_res_deprot_solv/joulesPerCalorie,...
				'k-.', 'linewidth',1.8);
L10 = plot(E_omega_vec, Enl_l10_res_deprot_solv/joulesPerCalorie,...
				'b:', 'linewidth',1.8);
L15 = plot(E_omega_vec, Enl_l15_res_deprot_solv/joulesPerCalorie,...
				'm--', 'linewidth',1.8);
xlabel('Solute Dielectric Constant   \epsilon_p');
ylabel('\Delta G_{solv}^{res} (deprotonated)');
axis([1.8 40 -85 -30]);

figure;
LH1 = plot(E_omega_vec,-(dE_total_l(1,:)-dE_total_l(2,:))*scaleFact, ...
			  'bo-','linewidth',1.8,'markersize',8);
hold on;
NLH2 = plot(E_omega_vec,-(dE_l2_total_nl(1,:)-dE_l2_total_nl(2,:))*scaleFact,...
				'rs--','linewidth',1.8,'markersize',8);
NLH5 = plot(E_omega_vec,-(dE_l5_total_nl(1,:)-dE_l5_total_nl(2,:))*scaleFact,...
				'k^-.','linewidth',1.8,'markersize',8);
NLH10 = plot(E_omega_vec,-(dE_l10_total_nl(1,:)-dE_l10_total_nl(2,:))*scaleFact,...
				'bd:','linewidth',1.8,'markersize',8);
NLH15 = plot(E_omega_vec,-(dE_l15_total_nl(1,:)-dE_l15_total_nl(2,:))*scaleFact,...
				'mo--','linewidth',1.8,'markersize',6);
set(gca,'FontSize',16);
XH1 = xlabel('Solute Dielectric Constant   \epsilon_p');
YH1 = ylabel('\Delta \Delta pKa');
LegH2 = legend('Local','Nonlocal, \lambda = 2',...
					'Nonlocal, \lambda = 5',...
					'Nonlocal, \lambda = 10',...
					'Nonlocal, \lambda = 15',...
					'location','northeast');
axis([1.8 20 -0.1 +0.6]);
