function [B, C] = chargeCollocation_mesh(meshData,centroids,normals,areas,...
													  pqrData)

[G,dGdn] = coulombMatrixCollocation(meshData,centroids,normals, ...
												pqrData.xyz);

B = struct('DirichletTrace',G,...
			  'NeumannTrace', dGdn);

[slpToCharges,dlpToCharges] = computeChargePotentials(meshData,...
																  pqrData.xyz);

C = struct('slpToCharges', slpToCharges,...
			  'dlpToCharges', dlpToCharges);
